basePath: /
definitions:
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.Product:
    properties:
      discount:
        type: number
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
  models.ProductRequest:
    properties:
      discount:
        type: number
      price:
        type: number
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample swagger for Fiber
  title: Fiber Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login info
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Login
      tags:
      - Authentication
  /products:
    get:
      consumes:
      - application/json
      description: Get details of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create details of product
      parameters:
      - description: Product detail
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      security:
      - ApiKeyAuth: []
      summary: Create product
      tags:
      - Products
  /products/{productId}:
    delete:
      consumes:
      - application/json
      description: Update details of product
      parameters:
      - description: Product id
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - ApiKeyAuth: []
      summary: Update product
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: Get details of product
      parameters:
      - description: Product id
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Get product by id
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update details of product
      parameters:
      - description: Product id
        in: path
        name: productId
        required: true
        type: integer
      - description: Product detail
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      security:
      - ApiKeyAuth: []
      summary: Update product
      tags:
      - Products
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
